"""init db

Revision ID: 238a398e43dc
Revises: 
Create Date: 2020-03-10 00:07:36.467927

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '238a398e43dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
