"""tambah age

Revision ID: d6e770c9ba59
Revises: 5fe8cb7db626
Create Date: 2020-03-07 11:53:36.265926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6e770c9ba59'
down_revision = '5fe8cb7db626'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('puppy', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('puppy', 'age')
    # ### end Alembic commands ###
